### ISSUE TITLE
100 Servers overflows the server list

### ISSUE THREAD

**Issue by HappyCord** [FromSyntax/termful#1]
Having over 100 server causes an overflow of the server list and does not let me access other servers
![image](https://user-images.githubusercontent.com/66735773/188938488-309b65ad-7220-4b59-989e-6aa906ef812c.png)

**Comment by FromSyntax** [comment]
You can scroll your mouse to see the other servers.

**Comment by Isaiahmag** [comment]
> You can scroll your mouse up and down to see the other servers.

If you got a lot of folders open you can't.

**Comment by FromSyntax** [comment]
That's really odd since I can scroll here normally. Probably it is an issue with [Horizontal Server List](https://github.com/DiscordStyles/HorizontalServerList).

**Comment by Isaiahmag** [comment]
> 

I usually would use that but I toggled it off when using this theme. When I use Horizontal Server List alone it doesn't cause this issue.

**Comment by FromSyntax** [comment]
Theoretically it should behave just the same, since here HSL is being imported as an add-on. I'll try finding a workaround for this issue soon.

**Comment by FromSyntax** [comment]
I updated the HSL distribution path in the latest commit. Could you all try it?

**Comment by HappyCord** [comment]
Just tried it, same thing.

**Comment by FromSyntax** [comment]
It really seems to be an issue with HSL. I'll report it to HSL's dev team. I will just disable centering for now, since letting it in the left doesn't cause this issue.

**Comment by FromSyntax** [comment]
Probably fixed in https://github.com/FromSyntax/termful/commit/7cca03785a6a5d61aa48375f4d29b939e3b16533. Only mentioned #2 since it also fixes that issue.

**Comment by FromSyntax** [comment]
Since I didn't get any reply back, I will assume this is fixed. Please reopen if you have any issue similar to this.
