### ISSUE TITLE
Unread Dot Beside Server Icon Is Missing

### ISSUE THREAD

**Issue by DoctorJax** [FromSyntax/termful#2]
As the title says, the little white unread dot beside of a server icon is missing. 

In normal Discord without theme:
![image](https://user-images.githubusercontent.com/72826197/189243680-6231b258-0511-4506-a860-2224117121cb.png)

With termful theme:
![image](https://user-images.githubusercontent.com/72826197/189243868-2dd960bd-2746-454a-94f4-da75473f7e16.png)

The only thing I changed between the two screenshots was the theme, so there should be a white dot under the server icon, but as you can see, there isn't.

**Comment by FromSyntax** [comment]
I updated the HSL distribution path in the latest commit. Could you try it?

**Comment by FromSyntax** [comment]
Okay, seems the problem was in my code. The `pill-` class was being hidden. I'm fixing it alongside #1, it will take only a few minutes to fix it.

**Comment by DoctorJax** [comment]
Ok great. I was just testing it and it still wasn't fixed. I'll test it again when you get it fixed. Thanks

**Comment by FromSyntax** [comment]
Probably fixed in latest commit. Could you try it?

**Comment by DoctorJax** [comment]
Yup, it's fixed. Even shows which server I'm on too.
![image](https://user-images.githubusercontent.com/72826197/189399433-c012e3d0-1edc-45ae-94b5-0c35e4cb0b5c.png)

Thanks!

**Comment by DoctorJax** [comment]
Fixed as of commit [7cca037](https://github.com/FromSyntax/termful/commit/7cca03785a6a5d61aa48375f4d29b939e3b16533) so I'll go ahead and close this issue.
